

* TXL – High-quality machine translation in Emacs via DeepL’s REST API
TXL provides machine translation through DeepL's REST API.

** Installation
TXL is in an early stage and therefore not yet available on MELPA or similar repositories.  The file [[https://github.com/tmalsburg/txl.el/blob/master/txl.el][txl.el]] must be downloaded and installed manually in a directory where Emacs will find it.

Dependencies are:
- [[https://github.com/tmalsburg/guess-language.el][guess-language.el]] (available on [[http://elpa.gnu.org/packages/guess-language.html][ELPA]])
- [[https://github.com/tkf/emacs-request][request.el]] (available on [[https://melpa.org/#/request][MELPA]])

** Configuration
Minimally the user needs to specify a pair of languages in the customization variable ~txl-languages~ and an authentication key for DeepL's REST API via ~txl-deepl-api-url~.  Example:

#+BEGIN_SRC elisp
(require 'txl)
(setq txl-languages '("DE" . "EN-US"))
(setq txl-deepl-api-key "my-api-key")
#+END_SRC

Other configuration variables are ~txl-deelp-split-sentences~, ~txl-deepl-preserve-formatting~, and ~txl-deepl-formality~.  See inline documentation for details.

** Usage
The command ~txl-translate-to-other-language~ translates the marked region or paragraph to the respective other language.  (The current language is detected using the ~guess-language~ package.)  The command ~txl-translate-roundtrip~ translates to the other language and back, which can yield alternative, sometimes more idiomatic formulations.  Both of these commands display the translation in the mini-buffer.  Alternatively the commands ~txl-replace-with-other-language~ and ~txl-replace-with-roundtrip~ can be used to replace the paragraph or marked region with the translation.

** Future versions
Many useful extensions are conceivable.  For instance, support for more than two languages and support for other translation backends.  Ideas and PRs are welcome.
